# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
# Your code goes here
import pandas as pd
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
df = pd.read_csv(url)

url_2 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
df_2 = pd.read_csv(url_2)

url_3 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv'
df_3 = pd.read_csv(url_3)

In [3]:
files = [url, url_2, url_3]
df_list = [pd.read_csv(f) for f in files]

In [4]:
df_combined = pd.concat(df_list, axis=0, ignore_index=True)

In [ ]:
def clean_data(df):  
    df.columns = [c.lower() for c in df.columns]
    df_copy = df_copy.dropna(how='all')
    df_copy.columns = [c.lower().replace(' ', '_') for c in df_copy.columns]
    return df
df_final = clean_data(df_combined)

In [7]:
df_final.head()

,customer,st,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount,state,gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,NaN,NaN
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,NaN,NaN

In [15]:
print(df_final.columns)

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount', 'state',
       'gender'],
      dtype='object')

In [ ]:
indices = [i for i, col in enumerate(df_final.columns) if col == 'gender']

print(f"Les columnes 'gender' estan a les posicions: {indices}")


display(df_final.iloc[:, indices].head(100))

Les columnes 'gender' estan a les posicions: [2, 12]

   gender gender
0     NaN    NaN
1       F    NaN
2       F    NaN
3       M    NaN
4       M    NaN
..    ...    ...
95    NaN    NaN
96    NaN    NaN
97    NaN    NaN
98    NaN    NaN
99    NaN    NaN

[100 rows x 2 columns]

In [19]:

indices = [i for i, col in enumerate(df_final.columns) if col == 'gender']

df_final.iloc[:, indices[0]] = df_final.iloc[:, indices[0]].fillna(df_final.iloc[:, indices[1]])

gender_correcte = df_final.iloc[:, indices[0]]
df_final = df_final.drop(columns=['gender'])
df_final['gender'] = gender_correcte

print(df_final['gender'].value_counts(dropna=False))

gender
F         4560
M         4368
NaN        122
Male        40
female      30
Femal       17
Name: count, dtype: int64

In [ ]:

mapeig = {
    'Male': 'M',
    'male': 'M',
    'M': 'M',
    'Female': 'F',
    'female': 'F',
    'Femal': 'F',
    'F': 'F'
}

df_final['gender'] = df_final['gender'].map(mapeig)

df_final = df_final.dropna(subset=['gender'])

print(df_final['gender'].value_counts(dropna=False))

gender
F    4607
M    4408
Name: count, dtype: int64

In [21]:
for col in df_final.columns:
    print(f"--- Columna: {col} ---")
    print(df_final[col].value_counts(dropna=False))
    print("\n")

--- Columna: customer ---
customer
LY14355    2
BW94308    2
SA54664    2
CI38330    2
RI52095    2
          ..
DG30586    1
JZ63423    1
NX18821    1
NI49607    1
Y167826    1
Name: count, Length: 8934, dtype: int64


--- Columna: st ---
st
NaN           7070
Oregon         579
California     451
Arizona        316
Nevada         214
Washington     174
Cali           119
AZ              63
WA              29
Name: count, dtype: int64


--- Columna: education ---
education
Bachelor                2676
College                 2647
High School or Below    2584
Master                   742
Doctor                   342
Bachelors                 24
Name: count, dtype: int64


--- Columna: customer lifetime value ---
customer lifetime value
2647.519741     6
4650.063763     6
5169.499370     6
6521.368813     6
2300.691547     6
               ..
19185.072500    1
2880.348532     1
4354.398727     1
14166.203440    1
2611.836866     1
Name: count, Length: 8104, dtype: int64


--- Columna: income ---
income
0.0        2270
95697.0      13
61108.0       8
26876.0       8
10621.0       8
           ...
91580.0       1
26746.0       1
62076.0       1
87421.0       1
21941.0       1
Name: count, Length: 5577, dtype: int64


--- Columna: monthly premium auto ---
monthly premium auto
65.0     346
66.0     308
73.0     299
71.0     299
67.0     285
        ...
204.0      1
281.0      1
237.0      1
275.0      1
286.0      1
Name: count, Length: 208, dtype: int64


--- Columna: number of open complaints ---
number of open complaints
0         5629
1/0/00    1540
1          765
2          283
3          230
1/1/00     228
4          119
1/2/00      84
1/3/00      53
5           44
1/4/00      29
1/5/00      11
Name: count, dtype: int64


--- Columna: policy type ---
policy type
Personal Auto     6700
Corporate Auto    1941
Special Auto       374
Name: count, dtype: int64


--- Columna: vehicle class ---
vehicle class
Four-Door Car    4569
Two-Door Car     1874
SUV              1754
Sports Car        478
Luxury SUV        180
Luxury Car        160
Name: count, dtype: int64


--- Columna: total claim amount ---
total claim amount
316.800000    117
292.800000    110
312.000000    107
350.400000    105
331.200000    102
             ...
579.467191      1
79.463916       1
40.287304       1
241.077843      1
790.784983      1
Name: count, Length: 5003, dtype: int64


--- Columna: state ---
state
California    2544
Oregon        1978
NaN           1945
Arizona       1302
Nevada         659
Washington     587
Name: count, dtype: int64


--- Columna: gender ---
gender
F    4607
M    4408
Name: count, dtype: int64

In [22]:
df_final['state'] = df_final['state'].fillna(df_final['st'])

In [23]:
df_final = df_final.drop(columns=['st'])

In [24]:

state_map = {
    'Cali': 'California',
    'AZ': 'Arizona',
    'WA': 'Washington',
    
}

df_final['state'] = df_final['state'].replace(state_map)

In [25]:
print(df_final['state'].value_counts(dropna=False))

state
California    3114
Oregon        2557
Arizona       1681
Nevada         873
Washington     790
Name: count, dtype: int64

In [26]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9015 entries, 1 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9015 non-null   object
 1   education                  9015 non-null   object
 2   customer lifetime value    9010 non-null   object
 3   income                     9015 non-null   float64
 4   monthly premium auto       9015 non-null   float64
 5   number of open complaints  9015 non-null   object
 6   policy type                9015 non-null   object
 7   vehicle class              9015 non-null   object
 8   total claim amount         9015 non-null   float64
 9   state                      9015 non-null   object
 10  gender                     9015 non-null   object
dtypes: float64(3), object(8)
memory usage: 845.2+ KB

In [27]:
df_final = df_final.dropna(how='all')
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9015 entries, 1 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9015 non-null   object
 1   education                  9015 non-null   object
 2   customer lifetime value    9010 non-null   object
 3   income                     9015 non-null   float64
 4   monthly premium auto       9015 non-null   float64
 5   number of open complaints  9015 non-null   object
 6   policy type                9015 non-null   object
 7   vehicle class              9015 non-null   object
 8   total claim amount         9015 non-null   float64
 9   state                      9015 non-null   object
 10  gender                     9015 non-null   object
dtypes: float64(3), object(8)
memory usage: 845.2+ KB

In [28]:
df_final.head()

,customer,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount,state,gender
1,QZ44356,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,Arizona,F
2,AI49188,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,Nevada,F
3,WW63253,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,California,M
4,GA49547,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,Washington,M
5,OC83172,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042,Oregon,F

In [30]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9015 entries, 1 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9015 non-null   object
 1   education                  9015 non-null   object
 2   customer lifetime value    9010 non-null   object
 3   income                     9015 non-null   float64
 4   monthly premium auto       9015 non-null   float64
 5   number of open complaints  9015 non-null   object
 6   policy type                9015 non-null   object
 7   vehicle class              9015 non-null   object
 8   total claim amount         9015 non-null   float64
 9   state                      9015 non-null   object
 10  gender                     9015 non-null   object
dtypes: float64(3), object(8)
memory usage: 845.2+ KB

In [31]:
df_final['customer lifetime value'] = df_final['customer lifetime value'].str.replace('%', '')
df_final['customer lifetime value'] = pd.to_numeric(df_final['customer lifetime value'], errors='coerce')

In [ ]:
df_final.columns = [c.lower().replace(' ', '_') for c in df_final.columns]


print(df_final.columns)

Index(['customer', 'education', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'number_of_open_complaints', 'policy_type',
       'vehicle_class', 'total_claim_amount', 'state', 'gender'],
      dtype='object')

In [34]:
df_final['number_of_open_complaints'] = df_final['number_of_open_complaints'].apply(lambda x: str(x).split('/')[0] if '/' in str(x) else x)


df_final['number_of_open_complaints'] = pd.to_numeric(df_final['number_of_open_complaints'], errors='coerce').fillna(0).astype(int)


print(df_final['number_of_open_complaints'].value_counts())

number_of_open_complaints
0    5629
1    2710
2     283
3     230
4     119
5      44
Name: count, dtype: int64

In [35]:
df_final.head()

,customer,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
1,QZ44356,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935,Arizona,F
2,AI49188,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247,Nevada,F
3,WW63253,Bachelor,764586.18,0.0,106.0,1,Corporate Auto,SUV,529.881344,California,M
4,GA49547,High School or Below,536307.65,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323,Washington,M
5,OC83172,Bachelor,825629.78,62902.0,69.0,1,Personal Auto,Two-Door Car,159.383042,Oregon,F

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [36]:
# Your code goes here
import pandas as pd
url_chall2 = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv'
df_chall2 = pd.read_csv(url_chall2)

In [37]:
df_chall2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [38]:
df_chall2.describe().T

,count,mean,std,min,25%,50%,75%,max
unnamed:_0,10910.0,5454.500000,3149.590053,0.000000,2727.250000,5454.500000,8181.750000,10909.000000
customer_lifetime_value,10910.0,8018.241094,6885.081434,1898.007675,4014.453113,5771.147235,8992.779137,83325.381190
income,10910.0,37536.284785,30359.195670,0.000000,0.000000,33813.500000,62250.750000,99981.000000
monthly_premium_auto,10910.0,93.196059,34.442532,61.000000,68.000000,83.000000,109.000000,298.000000
months_since_last_claim,10910.0,15.149071,9.783520,0.000000,7.000000,15.000000,23.000000,35.000000
months_since_policy_inception,10910.0,48.091934,27.940675,0.000000,24.000000,48.000000,71.000000,99.000000
number_of_open_complaints,10910.0,0.384256,0.885589,0.000000,0.000000,0.000000,0.384256,5.000000
number_of_policies,10910.0,2.979193,2.399359,1.000000,1.000000,2.000000,4.000000,9.000000
total_claim_amount,10910.0,434.888330,292.180556,0.099007,271.082527,382.564630,547.200000,2893.239678
month,10910.0,1.466728,0.498915,1.000000,1.000000,1.000000,2.000000,2.000000

In [39]:
df_chall2.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [41]:
if 'unnamed:_0' in df_chall2.columns:
    df_chall2 = df_chall2.drop(columns=['unnamed:_0'])

df_chall2['effective_to_date'] = pd.to_datetime(df_chall2['effective_to_date'])

df_chall2['number_of_open_complaints'] = df_chall2['number_of_open_complaints'].astype(int)

df_chall2 = df_chall2.drop_duplicates()

df_chall2.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [42]:
pivot_revenue = df_chall2.pivot_table(index='sales_channel', 
                                      values='total_claim_amount', 
                                      aggfunc='sum')


pivot_revenue = pivot_revenue.round(2)


pivot_revenue = pivot_revenue.sort_values(by='total_claim_amount', ascending=False)


display(pivot_revenue)

               total_claim_amount
sales_channel
Agent                  1748923.49
Branch                 1259333.44
Call Center             889094.77
Web                     676658.10

In [44]:
print(df_chall2['sales_channel'].unique())
#intentando buscar mail dentro de sales channel.
print(df_chall2['sales_channel'].value_counts())

['Agent' 'Call Center' 'Branch' 'Web']
sales_channel
Agent          3964
Branch         2910
Call Center    2046
Web            1547
Name: count, dtype: int64

In [45]:
#insights: el agente es la mayor fuente de ingresos de la empresa, seguida del branch, la web es la que menos ingresos genera. A lo mejor una inversión en la web para mejorar el marqueting podria mejorar dichos ingresos.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [46]:
pivot_clv = df_chall2.pivot_table(index=['gender', 'education'], 
                                  values='customer_lifetime_value', 
                                  aggfunc='mean')


pivot_clv = pivot_clv.round(2)


display(pivot_clv)

                             customer_lifetime_value
gender education
F      Bachelor                              7913.45
       College                               7755.03
       Doctor                                7369.59
       High School or Below                  8616.66
       Master                                8226.36
M      Bachelor                              7713.30
       College                               8086.29
       Doctor                                7414.86
       High School or Below                  8162.36
       Master                                8154.61

In [47]:
#las mujeres con high school or below tienen el clv más alto, pasa lo mismo con el sector de los hombres, auin que en general el clv es más bajo que en las mujeres. Podemos ver que el doctorado, es el que menos valor tienen. por tanto, le diria a la empresa que se centrada en clientes con estudios no tan altos como doctorado, y que ronden master y high school, que tienen el clv más alto.  Y que hagan campanyas para fidelizar este tipo de clientes

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here